In [1]:
import pandas as pd

In [2]:
import mysql.connector as connection

In [137]:
mydb = connection.connect(host="localhost", user="root", passwd="",database="practice")

In [138]:
print(mydb)

<mysql.connector.connection_cext.CMySQLConnection object at 0x0000017DB6EB5160>

In [139]:
cursor = mydb.cursor()

In [58]:
data = pd.read_excel(r'C:\Users\Pranshu Chaurasia\Desktop\data-science-bootcamp\data-science-bootcamp\python-assignment\dataset\Dress Sales.xlsx')

In [59]:
data.to_csv('C:\\Users\\Pranshu Chaurasia\\Desktop\\data-science-bootcamp\\data-science-bootcamp\\python-assignment\\dataset\\Dress Sales.csv',index=False)

In [60]:
data1=data = pd.read_csv(r'C:\Users\Pranshu Chaurasia\Desktop\data-science-bootcamp\data-science-bootcamp\python-assignment\dataset\Dress Sales.csv',header=None)

In [102]:
print(data1)

             0          1          2                    3   \
0      Dress_ID  29/8/2013  31/8/2013  2013-02-09 00:00:00
1    1006032852       2114       2274                 2491
2    1212192089        151        275                  570
3    1190380701          6          7                    7
4     966005983       1005       1128                 1326
..          ...        ...        ...                  ...
496   713391965          0          0                    0
497   722565148          0          0                    0
498   532874347          0          0                    0
499   655464934          0          0                    0
500   919930954          0          0                    0

                      4                    5                    6   \
0    2013-04-09 00:00:00  2013-06-09 00:00:00  2013-08-09 00:00:00
1                   2660                 2727                 2887
2                    750                  813                 1066
3                      7                    8                    8
4                   1455                 1507                 1621
..                   ...                  ...                  ...
496                  560                  554                  544
497                  875                  866                  861
498                  734                  728                  726
499                  254                  259                  261
500                  538                  545                  558

                      7                    8          9   ...         14  \
0    2013-10-09 00:00:00  2013-12-09 00:00:00  14/9/2013  ...  24/9/2013
1                   2930                 3119       3204  ...       3554
2                   1164                 1558       1756  ...       2710
3                      9                   10         10  ...         11
4                   1637                 1723       1746  ...       1878
..                   ...                  ...        ...  ...        ...
496                  537                  525        519  ...        400
497                  854                  850        844  ...        859
498                  715                  694        690  ...        616
499                  263                  268        270  ...        257
500                  563                  578        585  ...        628

            15         16         17                   18  \
0    26/9/2013  28/9/2013  30/9/2013  2013-02-10 00:00:00
1       3624.0       3706     3746.0               3795.0
2       2942.0       3258     3354.0               3475.0
3         11.0         11       11.0                 11.0
4       1892.0       1914     1924.0               1929.0
..         ...        ...        ...                  ...
496      388.0        360      364.0                372.0
497      866.0        882      888.0                895.0
498      597.0        586      569.0                561.0
499      256.0        255      254.0                253.0
500      632.0        639      645.0                651.0

                      19                   20                   21  \
0    2013-04-10 00:00:00  2013-06-10 00:00:00  2010-08-10 00:00:00
1                 3832.0                 3897               3923.0
2                 3654.0                 3911               4024.0
3                   11.0                   11                 11.0
4                 1941.0                 1952               1955.0
..                   ...                  ...                  ...
496                377.0                  380                382.0
497                898.0                  906                913.0
498                555.0                  551                546.0
499                250.0                  249                249.0
500                655.0                  660                668.0

                      22                   23
0    2013-10-10 00:00:00  2013-12-10 00:00:00
1                 3985.0                 4048
2                 4125.0                 4277
3                   11.0                   11
4                 1959.0                 1963
..                   ...                  ...
496                384.0                  285
497                919.0                  931
498                535.0                  520
499                249.0                  248
500                674.0                  680

[501 rows x 24 columns]

In [103]:
df = pd.DataFrame(data1)

In [63]:
df.shape

(501, 24)

In [64]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23],
           dtype='int64')

In [65]:
df.dtypes

0     object
1     object
2     object
3     object
4     object
5     object
6     object
7     object
8     object
9     object
10    object
11    object
12    object
13    object
14    object
15    object
16    object
17    object
18    object
19    object
20    object
21    object
22    object
23    object
dtype: object

In [17]:
#cursor.execute(" create table if not exists dress_dataset (Dress_ID INT,`29/8/2013` INT,`31/8/2013`	INT,`09-02-2013` INT,`09-04-2013` INT,`09-06-2013` INT,`09-08-2013` INT,`09-10-2013` INT,`09-12-2013` INT,`14/9/2013` INT,`16/9/2013` INT,`18/9/2013`  INT,`20/9/2013` INT,`22/9/2013` INT,`24/9/2013` INT,`26/9/2013` INT,`28/9/2013`	 INT,`30/9/2013` INT,`10-02-2013` INT,`10-04-2013` INT,`10-06-2013` INT,`10-10-2013` INT,`10-12-2013` INT)")

In [151]:
print(df.shape[0])

501

In [66]:
for row in df.itertuples():
    print(row)

Pandas(Index=0, _1='Dress_ID', _2='29/8/2013', _3='31/8/2013', _4='2013-02-09 00:00:00', _5='2013-04-09 00:00:00', _6='2013-06-09 00:00:00', _7='2013-08-09 00:00:00', _8='2013-10-09 00:00:00', _9='2013-12-09 00:00:00', _10='14/9/2013', _11='16/9/2013', _12='18/9/2013', _13='20/9/2013', _14='22/9/2013', _15='24/9/2013', _16='26/9/2013', _17='28/9/2013', _18='30/9/2013', _19='2013-02-10 00:00:00', _20='2013-04-10 00:00:00', _21='2013-06-10 00:00:00', _22='2010-08-10 00:00:00', _23='2013-10-10 00:00:00', _24='2013-12-10 00:00:00')
Pandas(Index=1, _1='1006032852', _2='2114', _3='2274', _4='2491', _5='2660', _6='2727', _7='2887', _8='2930', _9='3119', _10='3204', _11='3277', _12='3321', _13='3386', _14='3479', _15='3554', _16='3624.0', _17='3706', _18='3746.0', _19='3795.0', _20='3832.0', _21='3897', _22='3923.0', _23='3985.0', _24='4048')
Pandas(Index=2, _1='1212192089', _2='151', _3='275', _4='570', _5='750', _6='813', _7='1066', _8='1164', _9='1558', _10='1756', _11='1878', _12='1985', _13='2106', _14='2454', _15='2710', _16='2942.0', _17='3258', _18='3354.0', _19='3475.0', _20='3654.0', _21='3911', _22='4024.0', _23='4125.0', _24='4277')
Pandas(Index=3, _1='1190380701', _2='6', _3='7', _4='7', _5='7', _6='8', _7='8', _8='9', _9='10', _10='10', _11='10', _12='10', _13='10', _14='11', _15='11', _16='11.0', _17='11', _18='11.0', _19='11.0', _20='11.0', _21='11', _22='11.0', _23='11.0', _24='11')
Pandas(Index=4, _1='966005983', _2='1005', _3='1128', _4='1326', _5='1455', _6='1507', _7='1621', _8='1637', _9='1723', _10='1746', _11='1783', _12='1796', _13='1812', _14='1845', _15='1878', _16='1892.0', _17='1914', _18='1924.0', _19='1929.0', _20='1941.0', _21='1952', _22='1955.0', _23='1959.0', _24='1963')
Pandas(Index=5, _1='876339541', _2='996', _3='1175', _4='1304', _5='1396', _6='1432', _7='1559', _8='1570', _9='1638', _10='1655', _11='1681', _12='1743', _13='1824', _14='1919', _15='2032', _16='2156.0', _17='2252', _18='2312.0', _19='2387.0', _20='2459.0', _21='2544', _22='2614.0', _23='2693.0', _24='2736')
Pandas(Index=6, _1='1068332458', _2='4', _3='5', _4='11', _5='13', _6='13', _7='13', _8='16', _9='18', _10='19', _11='20', _12='20', _13='21', _14='22', _15='25', _16='25.0', _17='26', _18='26.0', _19='26.0', _20='26.0', _21='27', _22='27.0', _23='27.0', _24='27')
Pandas(Index=7, _1='1220707172', _2='45', _3='61', _4='131', _5='165', _6='176', _7='209', _8='216', _9='251', _10='262', _11='289', _12='295', _13='325', _14='353', _15='379', _16='400.0', _17='417', _18='424.0', _19='445.0', _20='462.0', _21='474', _22='494.0', _23='503.0', _24='552')
Pandas(Index=8, _1='1219677488', _2='4', _3='13', _4='55', _5='73', _6='76', _7='89', _8='94', _9='117', _10='121', _11='125', _12='135', _13='142', _14='150', _15='160', _16='165.0', _17='169', _18='172.0', _19='196.0', _20='212.0', _21='224', _22='241.0', _23='252.0', _24='263')
Pandas(Index=9, _1='1113094204', _2='5', _3='6', _4='10', _5='12', _6='13', _7='15', _8='16', _9='17', _10='17', _11='19', _12='21', _13='25', _14='27', _15='27', _16='28.0', _17='29', _18='29.0', _19='29.0', _20='29.0', _21='29', _22='29.0', _23='29.0', _24='33')
Pandas(Index=10, _1='985292672', _2='9', _3='11', _4='12', _5='12', _6='12', _7='12', _8='12', _9='13', _10='13', _11='13', _12='13', _13='14', _14='14', _15='14', _16='14.0', _17='14', _18='14.0', _19='14.0', _20='14.0', _21='14', _22='14.0', _23='14.0', _24='14')
Pandas(Index=11, _1='1117293701', _2='15', _3='28', _4='42', _5='49', _6='49', _7='55', _8='56', _9='65', _10='66', _11='68', _12='68', _13='78', _14='89', _15='93', _16='98.0', _17='106', _18='114.0', _19='119.0', _20='124.0', _21='128', _22='130.0', _23='133.0', _24='138')
Pandas(Index=12, _1='898481530', _2='23', _3='38', _4='54', _5='59', _6='65', _7='72', _8='77', _9='90', _10='102', _11='106', _12='117', _13='122', _14='133', _15='153', _16='162.0', _17='170', _18='172.0', _19='176.0', _20='181.0', _21='185', _22='188.0', _23='195.0', _24='202')
Pandas(Index=13, _1='957723897', _2='1235', _3='1333', _4='1471', _5='1568', _6='1602', _7='1722', _8='1756', _9='1906', _10='1994', _11='2077', _12='2105', _13='2192', _14='2284', _15='2395', _16='2423.0', _17='2537', _18='2580.0', _19='2645.0', _20='2704.0', _21='2748', _22='2813.0', _23='2914.0', _24='2979')
Pandas(Index=14, _1='749031896', _2='2498', _3='2545', _4='2627', _5='2656', _6='2669', _7='2738', _8='2769', _9='2934', _10='3001', _11='3068', _12='3125', _13='3239', _14='3339', _15='3445', _16='3561.0', _17='3667', _18='3680.0', _19='3745.0', _20='3842.0', _21='3952', _22='3999.0', _23='4077.0', _24='4170')
Pandas(Index=15, _1='1055411544', _2='22', _3='28', _4='40', _5='43', _6='44', _7='45', _8='45', _9='49', _10='50', _11='51', _12='51', _13='52', _14='53', _15='52', _16='52.0', _17='52', _18='52.0', _19='52.0', _20='52.0', _21='52', _22='52.0', _23='53.0', _24='53')
Pandas(Index=16, _1='1162628131', _2='4', _3='8', _4='19', _5='25', _6='26', _7='31', _8='35', _9='45', _10='48', _11='58', _12='74', _13='88', _14='97', _15='120', _16='132.0', _17='158', _18='163.0', _19='174.0', _20='182.0', _21='195', _22='204.0', _23='213.0', _24='220')
Pandas(Index=17, _1='624314841', _2='1587', _3='1669', _4='1729', _5='1764', _6='1782', _7='1817', _8='1833', _9='1898', _10='1909', _11='1954', _12='2005', _13='2096', _14='2120', _15='2163', _16='2241.0', _17='2301', _18='2325.0', _19='2375.0', _20='2421.0', _21='2479', _22='2492.0', _23='2512.0', _24='2526')
Pandas(Index=18, _1='830467746', _2='10', _3='13', _4='17', _5='17', _6='17', _7='17', _8='17', _9='17', _10='17', _11='17', _12='17', _13='18', _14='18', _15='18', _16='19.0', _17='19', _18='19.0', _19='19.0', _20='19.0', _21='19', _22='19.0', _23='19.0', _24='19')
Pandas(Index=19, _1='840857118', _2='2', _3='4', _4='10', _5='11', _6='11', _7='12', _8='12', _9='12', _10='13', _11='13', _12='13', _13='13', _14='13', _15='13', _16='13.0', _17='16', _18='16.0', _19='17.0', _20='17.0', _21='17', _22='17.0', _23='17.0', _24='17')
Pandas(Index=20, _1='1113221101', _2='122', _3='143', _4='243', _5='279', _6='299', _7='322', _8='331', _9='381', _10='401', _11='413', _12='442', _13='458', _14='470', _15='496', _16='517.0', _17='539', _18='542.0', _19='562.0', _20='575.0', _21='596', _22='602.0', _23='621.0', _24='644')
Pandas(Index=21, _1='861754372', _2='104', _3='106', _4='142', _5='163', _6='171', _7='192', _8='196', _9='227', _10='247', _11='258', _12='264', _13='285', _14='291', _15='316', _16='244.0', _17='365', _18='368.0', _19='369.0', _20='370.0', _21='372', _22='374.0', _23='375.0', _24='376')
Pandas(Index=22, _1='856178100', _2='856', _3='967', _4='1057', _5='1109', _6='1124', _7='1173', _8='1198', _9='1248', _10='1284', _11='1300', _12='1326', _13='1366', _14='1388', _15='1431', _16='1482.0', _17='1533', _18='1564.0', _19='1572.0', _20='1621.0', _21='1682', _22='1699.0', _23='1726.0', _24='1761')
Pandas(Index=23, _1='1122989777', _2='145', _3='189', _4='219', _5='229', _6='229', _7='233', _8='233', _9='233', _10='233', _11='233', _12='233', _13='233', _14='233', _15='233', _16='233.0', _17='233', _18='233.0', _19='233.0', _20='234.0', _21='235', _22='235.0', _23='236.0', _24='236')
Pandas(Index=24, _1='840516484', _2='1292', _3='1319', _4='1405', _5='1479', _6='1512', _7='1578', _8='1592', _9='1671', _10='1689', _11='1738', _12='1778', _13='1820', _14='1905', _15='1962', _16='1946.0', _17='2077', _18='2095.0', _19='2115.0', _20='2179.0', _21='2243', _22='2286.0', _23='2314.0', _24='2352')
Pandas(Index=25, _1='768517084', _2='2', _3='3', _4='4', _5='4', _6='4', _7='5', _8='5', _9='5', _10='5', _11='5', _12='5', _13='5', _14='5', _15='5', _16='5.0', _17='5', _18='5.0', _19='5.0', _20='5.0', _21='5', _22='5.0', _23='5.0', _24='5')
Pandas(Index=26, _1='1139843344', _2='6', _3='7', _4='15', _5='19', _6='19', _7='19', _8='20', _9='22', _10='22', _11='23', _12='23', _13='24', _14='25', _15='25', _16='26.0', _17='26', _18='27.0', _19='27.0', _20='28.0', _21='28', _22='29.0', _23='29.0', _24='29')
Pandas(Index=27, _1='1004212992', _2='986', _3='1048', _4='1224', _5='1358', _6='1401', _7='1571', _8='1612', _9='1762', _10='1852', _11='1901', _12='2041', _13='2115', _14='2217', _15='2358', _16='2452.0', _17='2580', _18='2621.0', _19='2678.0', _20='2792.0', _21='2882', _22='2923.0', _23='2995.0', _24='3071')
Pandas(Index=28, _1='1235426503', _2='6', _3='8', _4='25', _5='42', _6='49', _7='67', _8='76', _9='105', _10='114', _11='134', _12='154', _13='180', _14='215', _15='253', _16='275.0', _17='311', _18='328.0', _19='345.0', _20='367.0', _21='388', _22='392.0', _23='416.0', _24='446')
Pandas(Index=29, _1='942808364', _2='375', _3='421', _4='463', _5='475', _6='476', _7='483', _8='488', _9='497', _10='500', _11='505', _12='506', _13='510', _14='515', _15='523', _16='525.0', _17='526', _18='528.0', _19='530.0', _20='532.0', _21='533', _22='534.0', _23='536.0', _24='537')
Pandas(Index=30, _1='629131530', _2='7455', _3='7467', _4='7479', _5='7374', _6='7351', _7='7255', _8='7240', _9='7156', _10='7124', _11='7115', _12='7015', _13='6992', _14='6926', _15='6644', _16='6528.0', _17='6476', _18='6327.0', _19='6285.0', _20='6142.0', _21='6049', _22='5912.0', _23='5862.0', _24='5753')
Pandas(Index=31, _1='851945460', _2='1168', _3='1271', _4='1301', _5='1330', _6='1344', _7='1383', _8='1395', _9='1456', _10='1468', _11='1497', _12='1506', _13='1533', _14='1561', _15='1590', _16='1553.0', _17='1637', _18=nan, _19=nan, _20=nan, _21='1705', _22=nan, _23=nan, _24='1798')
Pandas(Index=32, _1='1150275464', _2='84', _3='130', _4='176', _5='205', _6='218', _7='272', _8='273', _9='279', _10='280', _11='284', _12='304', _13='334', _14='365', _15='417', _16='456.0', _17='494', _18=nan, _19=nan, _20=nan, _21='561', _22=nan, _23=nan, _24='606')
Pandas(Index=33, _1='1026634314', _2='804', _3='837', _4='897', _5='931', _6='937', _7='969', _8='974', _9='1004', _10='1008', _11='1019', _12='1024', _13='1045', _14='1051', _15='1060', _16='1086.0', _17='1103', _18=nan, _19=nan, _20=nan, _21='1177', _22=nan, _23=nan, _24='1258')
Pandas(Index=34, _1='978773911', _2='911', _3='946', _4='1035', _5='1085', _6='1105', _7='1159', _8='1185', _9='1244', _10='1288', _11='1304', _12='1347', _13='1370', _14='1402', _15='1455', _16='1488.0', _17='1525', _18=nan, _19=nan, _20=nan, _21='1642', _22=nan, _23=nan, _24='1709')
Pandas(Index=35, _1='827791337', _2='2184', _3='2228', _4='2309', _5='2313', _6='2313', _7='2315', _8='2315', _9='2321', _10='2330', _11='2336', _12='2339', _13='2347', _14='2358', _15='2363', _16='2366.0', _17='2369', _18=nan, _19=nan, _20=nan, _21='2381', _22=nan, _23=nan, _24='2388')
Pandas(Index=36, _1='640823350', _2='1134', _3='1482', _4='1562', _5='1595', _6='1604', _7='1645', _8='1648', _9='1706', _10='1752', _11='1785', _12='1796', _13='1811', _14='1841', _15='1602', _16='1622.0', _17='1637', _18=nan, _19=nan, _20=nan, _21='1657', _22=nan, _23=nan, _24='1649')
Pandas(Index=37, _1='801861988', _2='1576', _3='1680', _4='1729', _5='1730', _6='1730', _7='1743', _8='1743', _9='1744', _10='1746', _11='1749', _12='1766', _13='1789', _14='1817', _15='1882', _16='1910.0', _17='1949', _18=nan, _19=nan, _20=nan, _21='2008', _22=nan, _23=nan, _24='2051')
Pandas(Index=38, _1='1060207186', _2='19', _3='23', _4='45', _5='50', _6='53', _7='59', _8='62', _9='66', _10='71', _11='74', _12='79', _13='85', _14='93', _15='102', _16='102.0', _17='102', _18='103.0', _19='103.0', _20='105.0', _21='106', _22='106.0', _23='106.0', _24='106')
Pandas(Index=39, _1='1054679816', _2='175', _3='189', _4='262', _5='319', _6='345', _7='427', _8='463', _9='569', _10='596', _11='661', _12='674', _13='688', _14='907', _15='1114', _16='1175.0', _17='1267', _18=nan, _19=nan, _20=nan, _21='1499', _22=nan, _23=nan, _24='1657')
Pandas(Index=40, _1='941190190', _2='216', _3='261', _4='359', _5='398', _6='417', _7='473', _8='503', _9='557', _10='586', _11='612', _12='654', _13='678', _14='724', _15='852', _16='931.0', _17='1052', _18=nan, _19=nan, _20=nan, _21='1163', _22=nan, _23=nan, _24='1257')
Pandas(Index=41, _1='943844640', _2='48', _3='55', _4='83', _5='112', _6='116', _7='132', _8='134', _9='156', _10='157', _11='158', _12='164', _13='174', _14='181', _15='203', _16='230.0', _17='244', _18=nan, _19=nan, _20=nan, _21='304', _22=nan, _23=nan, _24='348')
Pandas(Index=42, _1='661795386', _2='2689', _3='2747', _4='2811', _5='2844', _6='2862', _7='2900', _8='2910', _9='2930', _10='2935', _11='2947', _12='2954', _13='2977', _14='2984', _15='2886', _16=nan, _17='2890', _18=nan, _19=nan, _20=nan, _21='2951', _22=nan, _23=nan, _24='2956')
Pandas(Index=43, _1='875312593', _2='416', _3='473', _4='520', _5='555', _6='564', _7='598', _8='611', _9='640', _10='650', _11='671', _12='693', _13='705', _14='725', _15='749', _16='757.0', _17='786', _18=nan, _19=nan, _20=nan, _21='836', _22=nan, _23=nan, _24='868')
Pandas(Index=44, _1='971387676', _2='624', _3='652', _4='716', _5='756', _6='771', _7='803', _8='820', _9='878', _10='897', _11='916', _12='928', _13='965', _14='1009', _15='1046', _16=nan, _17='1129', _18=nan, _19=nan, _20=nan, _21='1259', _22=nan, _23=nan, _24='1337')
Pandas(Index=45, _1='1021185637', _2='124', _3='144', _4='185', _5='197', _6='200', _7='215', _8='226', _9='240', _10='246', _11='254', _12='259', _13='268', _14='283', _15='301', _16='307.0', _17='315', _18=nan, _19=nan, _20=nan, _21='338', _22=nan, _23=nan, _24='349')
Pandas(Index=46, _1='1163826114', _2='3', _3='5', _4='32', _5='48', _6='56', _7='79', _8='82', _9='112', _10='117', _11='122', _12='131', _13='138', _14='144', _15='160', _16='172.0', _17='198', _18=nan, _19=nan, _20=nan, _21='251', _22=nan, _23=nan, _24='283')
Pandas(Index=47, _1='735635595', _2='5376', _3='5404', _4='5481', _5='5484', _6='5505', _7='5514', _8='5495', _9='5475', _10='5465', _11='5445', _12='5428', _13='5304', _14='5349', _15='5162', _16=nan, _17='5172', _18=nan, _19=nan, _20=nan, _21='5225', _22=nan, _23=nan, _24='5272')
Pandas(Index=48, _1='1175184188', _2='4', _3='5', _4='18', _5='23', _6='23', _7='24', _8='24', _9='24', _10='25', _11='25', _12='25', _13='26', _14='28', _15='30', _16='30.0', _17='33', _18='34.0', _19='36.0', _20='38.0', _21='39', _22='40.0', _23='40.0', _24='41')
Pandas(Index=49, _1='679415939', _2='995', _3='1091', _4='1141', _5='1165', _6='1173', _7='1190', _8='1189', _9='1210', _10='1221', _11='1245', _12='1262', _13='1276', _14='1302', _15='1324', _16=nan, _17='1322', _18=nan, _19=nan, _20=nan, _21='1313', _22=nan, _23=nan, _24='1311')
Pandas(Index=50, _1='884147971', _2='3', _3='3', _4='4', _5='4', _6='4', _7='4', _8='4', _9='4', _10='4', _11='4', _12='4', _13='4', _14='4', _15='5', _16='5.0', _17='5', _18='5.0', _19='5.0', _20='5.0', _21='4', _22='4.0', _23='4.0', _24='4')
Pandas(Index=51, _1='841203385', _2='114', _3='142', _4='165', _5='176', _6='181', _7='189', _8='191', _9='209', _10='215', _11='224', _12='234', _13='239', _14='249', _15='262', _16='268.0', _17='273', _18=nan, _19=nan, _20=nan, _21='298', _22=nan, _23=nan, _24='314')
Pandas(Index=52, _1='1117997056', _2='125', _3='143', _4='186', _5='198', _6='205', _7='215', _8='215', _9='218', _10='219', _11='224', _12='228', _13='232', _14='236', _15='242', _16='252.0', _17='260', _18=nan, _19=nan, _20=nan, _21='267', _22=nan, _23=nan, _24='282')
Pandas(Index=53, _1='1160536550', _2='19', _3='25', _4='40', _5='44', _6='47', _7='55', _8='56', _9='59', _10='59', _11='60', _12='62', _13='62', _14='64', _15='66', _16='66.0', _17='68', _18='68.0', _19='69.0', _20='70.0', _21='70', _22='70.0', _23='71.0', _24='71')
Pandas(Index=54, _1='828623528', _2='1397', _3='1403', _4='1412', _5='1415', _6='1417', _7='1425', _8='1433', _9='1474', _10='1492', _11='1516', _12='1535', _13='1564', _14='1581', _15='1602', _16='1623.0', _17='1638', _18=nan, _19=nan, _20=nan, _21='1696', _22=nan, _23=nan, _24='1741')
Pandas(Index=55, _1='763708514', _2='611', _3='666', _4='719', _5='766', _6='792', _7='841', _8='858', _9='921', _10='944', _11='962', _12='674', _13='998', _14='1060', _15='1114', _16='1147.0', _17='1195', _18=nan, _19=nan, _20=nan, _21='1330', _22=nan, _23=nan, _24='1481')
Pandas(Index=56, _1='1153442065', _2='84', _3='97', _4='146', _5='182', _6='195', _7='248', _8='263', _9='328', _10='231', _11='336', _12='375', _13='401', _14='460', _15='482', _16='483.0', _17='484', _18=nan, _19=nan, _20=nan, _21='519', _22=nan, _23=nan, _24='591')
Pandas(Index=57, _1='743729613', _2='304', _3='332', _4='400', _5='432', _6='444', _7='503', _8='520', _9='567', _10='583', _11='628', _12='665', _13='688', _14='723', _15='747', _16='756.0', _17='785', _18=nan, _19=nan, _20=nan, _21='873', _22=nan, _23=nan, _24='994')
Pandas(Index=58, _1='1000493051', _2='448', _3='470', _4='515', _5='536', _6='542', _7='558', _8='566', _9='585', _10='594', _11='605', _12='615', _13='621', _14='628', _15='637', _16=nan, _17='638', _18=nan, _19=nan, _20=nan, _21='642', _22=nan, _23=nan, _24='652')
Pandas(Index=59, _1='911085061', _2='214', _3='245', _4='302', _5='324', _6='329', _7='342', _8='343', _9='359', _10='371', _11='387', _12='394', _13='412', _14='428', _15='428', _16='432.0', _17='437', _18=nan, _19=nan, _20=nan, _21='482', _22=nan, _23=nan, _24='522')
Pandas(Index=60, _1='1174854264', _2='9', _3='13', _4='20', _5='23', _6='23', _7='26', _8='26', _9='30', _10='30', _11='30', _12='30', _13='31', _14='33', _15='36', _16='40.0', _17='42', _18='44.0', _19='45.0', _20='46.0', _21='48', _22='50.0', _23='51.0', _24='52')
Pandas(Index=61, _1='1053296757', _2='1', _3='2', _4='2', _5='4', _6='4', _7='4', _8='4', _9='4', _10='5', _11='5', _12='5', _13='5', _14='5', _15='5', _16='5.0', _17='5', _18='5.0', _19='5.0', _20='6.0', _21='6', _22='6.0', _23='6.0', _24='6')
Pandas(Index=62, _1='1033843327', _2='2', _3='3', _4='5', _5='5', _6='6', _7='7', _8='7', _9='8', _10='8', _11='9', _12='9', _13='10', _14='12', _15='12', _16='12.0', _17='13', _18='14.0', _19='16.0', _20='17.0', _21='19', _22='20.0', _23='21.0', _24='22')
Pandas(Index=63, _1='1083779666', _2='40', _3='41', _4='56', _5='57', _6='59', _7='62', _8='63', _9='68', _10='70', _11='72', _12='74', _13='75', _14='77', _15='76', _16='75.0', _17='75', _18='75.0', _19='75.0', _20='75.0', _21='75', _22='75.0', _23='75.0', _24='75')
Pandas(Index=64, _1='746255172', _2='1683', _3='1714', _4='1800', _5='1846', _6='1873', _7='1943', _8='1960', _9='2025', _10='2074', _11='2104', _12='2134', _13='2156', _14='2192', _15='2197', _16='2225.0', _17='2297', _18=nan, _19=nan, _20=nan, _21='2403', _22=nan, _23=nan, _24='2457')
Pandas(Index=65, _1='1100974555', _2='132', _3='149', _4='174', _5='206', _6='220', _7='244', _8='257', _9='293', _10='309', _11='337', _12='354', _13='385', _14='405', _15='437', _16=nan, _17='499', _18=nan, _19=nan, _20=nan, _21='582', _22=nan, _23=nan, _24='631')
Pandas(Index=66, _1='1019134411', _2='349', _3='397', _4='459', _5='513', _6='535', _7='582', _8='601', _9='670', _10='694', _11='724', _12='764', _13='775', _14='813', _15='879', _16=nan, _17='972', _18=nan, _19=nan, _20=nan, _21='1090', _22=nan, _23=nan, _24='1184')
Pandas(Index=67, _1='1072477320', _2='238', _3='243', _4='272', _5='308', _6='330', _7='373', _8='373', _9='375', _10='376', _11='379', _12='384', _13='405', _14='443', _15='474', _16=nan, _17='524', _18=nan, _19=nan, _20=nan, _21='586', _22=nan, _23=nan, _24='639')
Pandas(Index=68, _1='638423913', _2='24', _3='25', _4='25', _5='27', _6='27', _7='26', _8='26', _9='25', _10='26', _11='26', _12='26', _13='26', _14='26', _15='26', _16='26.0', _17='26', _18='26.0', _19='26.0', _20='26.0', _21='26', _22='27.0', _23='28.0', _24='29')
Pandas(Index=69, _1='936425780', _2='248', _3='294', _4='331', _5='358', _6='363', _7='380', _8='388', _9='415', _10='419', _11='437', _12='445', _13='457', _14='482', _15='499', _16='514.0', _17='536', _18=nan, _19=nan, _20=nan, _21='590', _22=nan, _23=nan, _24='619')

In [88]:
t= dict(df.iloc[1,:])
test_v=t.values()

In [104]:
tup=tuple(test_v)

In [94]:
print(len(tup))

24

In [93]:
print(type(cursor))

<class 'mysql.connector.cursor_cext.CMySQLCursor'>

In [144]:
sql = "INSERT INTO practice.dress_dataset values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"

In [96]:
cursor.execute(sql,tup)
mydb.commit()

In [136]:


l=[]
x=len(tup)
for i in range (x):
    if(i==0):
        l.append(int(tup[i]))
    else:
        l.append(float(tup[i]))
#print(l)
tup_new=tuple(l)
print(tup_new)

(1006032852, 2114.0, 2274.0, 2491.0, 2660.0, 2727.0, 2887.0, 2930.0, 3119.0, 3204.0, 3277.0, 3321.0, 3386.0, 3479.0, 3554.0, 3624.0, 3706.0, 3746.0, 3795.0, 3832.0, 3897.0, 3923.0, 3985.0, 4048.0)

In [142]:
#sql = "INSERT INTO practice.dress_dataset values(%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f)"

In [149]:
cursor.execute(sql,tup_new)
mydb.commit()

In [179]:
df.fillna(0)

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,Dress_ID,29/8/2013,31/8/2013,2013-02-09 00:00:00,2013-04-09 00:00:00,2013-06-09 00:00:00,2013-08-09 00:00:00,2013-10-09 00:00:00,2013-12-09 00:00:00,14/9/2013,...,24/9/2013,26/9/2013,28/9/2013,30/9/2013,2013-02-10 00:00:00,2013-04-10 00:00:00,2013-06-10 00:00:00,2010-08-10 00:00:00,2013-10-10 00:00:00,2013-12-10 00:00:00
1,1006032852,2114,2274,2491,2660,2727,2887,2930,3119,3204,...,3554,3624.0,3706,3746.0,3795.0,3832.0,3897,3923.0,3985.0,4048
2,1212192089,151,275,570,750,813,1066,1164,1558,1756,...,2710,2942.0,3258,3354.0,3475.0,3654.0,3911,4024.0,4125.0,4277
3,1190380701,6,7,7,7,8,8,9,10,10,...,11,11.0,11,11.0,11.0,11.0,11,11.0,11.0,11
4,966005983,1005,1128,1326,1455,1507,1621,1637,1723,1746,...,1878,1892.0,1914,1924.0,1929.0,1941.0,1952,1955.0,1959.0,1963
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,713391965,0,0,0,560,554,544,537,525,519,...,400,388.0,360,364.0,372.0,377.0,380,382.0,384.0,285
497,722565148,0,0,0,875,866,861,854,850,844,...,859,866.0,882,888.0,895.0,898.0,906,913.0,919.0,931
498,532874347,0,0,0,734,728,726,715,694,690,...,616,597.0,586,569.0,561.0,555.0,551,546.0,535.0,520
499,655464934,0,0,0,254,259,261,263,268,270,...,257,256.0,255,254.0,253.0,250.0,249,249.0,249.0,248
500,919930954,0,0,0,538,545,558,563,578,585,...,628,632.0,639,645.0,651.0,655.0,660,668.0,674.0,680

In [180]:
for j in range(df.shape[0]):
    if j==0:
        pass
    else:
        t= dict(df.iloc[j,:])
        test_v=t.values()
        tup=tuple(test_v)
        if(tup[0]=='851945460'):
            break

In [192]:
print(tup)
import numpy as np

('851945460', '1168', '1271', '1301', '1330', '1344', '1383', '1395', '1456', '1468', '1497', '1506', '1533', '1561', '1590', '1553.0', '1637', nan, nan, nan, '1705', nan, nan, '1798')

In [197]:
for i in range(24):
    if(type(tup[i]) == type('s')):
        s=type(tup[i])
        print(s)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

In [201]:
tex= dict(df.iloc[j,:])
test_v1=tex.values()
print(type(test_v1))
tup2=tuple(test_v1)
lt=[]
x=len(tup2)
for i in range (x):
    if(i==0):
        lt.append(int(tup2[i]))
    else:
        if(type(tup2[i])==type(3.0)):
            lt.append(0.0)
        else:
            lt.append(float(tup2[i]))
#print(l)
tup_new2=tuple(lt)
print(tup_new2)

<class 'dict_values'>
(851945460, 1168.0, 1271.0, 1301.0, 1330.0, 1344.0, 1383.0, 1395.0, 1456.0, 1468.0, 1497.0, 1506.0, 1533.0, 1561.0, 1590.0, 1553.0, 1637.0, 0.0, 0.0, 0.0, 1705.0, 0.0, 0.0, 1798.0)

In [203]:
for i in range(24):
    print(type(tup_new2[i]))

<class 'int'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>